# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Pop
exclude: [CNAME, package.json, node_modules]
gems: [jekyll-sass]
sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: true
